### ISSUE TITLE
rejoins previous meeting

### ISSUE THREAD

**Issue by Raboo** [micoli/electron-meet#1]
Hi,

I have found a bug.

I started electron-meet and created a meeting "test".
I left the meeting, returned to main screen, quit electron-meet.
Started electron-meet again, it automatically joined the meeting "test".
It should always start in the main screen?

**Comment by eliezerlp** [comment]
This is actually a feature. You can right click on the tray icon to control the behavior.

**Comment by Raboo** [comment]
ok
